# Generated by Django 3.2 on 2021-04-20 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleofAudio', models.CharField(max_length=99)),
                ('authorofTitle', models.CharField(max_length=99)),
                ('narator', models.CharField(max_length=99)),
                ('duration', models.PositiveIntegerField()),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofPodcast', models.CharField(max_length=99)),
                ('duration', models.PositiveIntegerField()),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=99)),
                ('participants', models.CharField(max_length=99, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofSong', models.CharField(max_length=99)),
                ('durinsec', models.PositiveIntegerField()),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
